import 'package:flutter/material.dart';

import '../../models/models.dart';

final inventoryStatusReport = ReportDefinition(
  id: 'inventory-status',
  title: 'Inventory Status',
  description: 'Real-time inventory levels, stock alerts, and category breakdown',
  category: 'Inventory',
  icon: Icons.inventory_2,
  datasource: 'inventory-status',
  filters: const [
    FilterDefinition(
      id: 'category',
      label: 'Category',
      type: ReportFilterType.singleSelect,
      apiEndpoint: '/api/categories',
    ),
    FilterDefinition(
      id: 'product',
      label: 'Product',
      type: ReportFilterType.searchableDropdown,
      apiEndpoint: '/api/products',
    ),
    FilterDefinition(
      id: 'lowStockOnly',
      label: 'Low Stock Only',
      type: ReportFilterType.boolean,
      defaultValue: false,
    ),
  ],
  cards: [
    CardDefinition(
      id: 'total-items',
      title: 'Total Items in Stock',
      dataKey: 'totalItems',
      trendKey: 'totalItemsTrend',
      icon: Icons.inventory,
      color: const Color(0xFF1565C0),
    ),
    CardDefinition(
      id: 'low-stock',
      title: 'Low Stock Alerts',
      dataKey: 'lowStockCount',
      trendKey: 'lowStockCountTrend',
      icon: Icons.warning_amber,
      color: const Color(0xFFC62828),
    ),
    CardDefinition(
      id: 'total-value',
      title: 'Total Inventory Value',
      dataKey: 'totalValue',
      trendKey: 'totalValueTrend',
      icon: Icons.attach_money,
      color: const Color(0xFF2E7D32),
      isCurrency: true,
    ),
    CardDefinition(
      id: 'turnover',
      title: 'Turnover Rate',
      dataKey: 'turnoverRate',
      trendKey: 'turnoverRateTrend',
      icon: Icons.speed,
      color: const Color(0xFFF57C00),
      formatString: '#0.0x',
    ),
  ],
  charts: [
    ChartDefinition(
      id: 'category-breakdown',
      title: 'Inventory by Category',
      subtitle: 'Item count distribution across categories',
      chartType: ReportChartType.doughnut,
      dataKey: 'byCategory',
      xField: 'category',
      yFields: ['count'],
      legend: const ChartLegendConfig(visible: true, position: 'right'),
      tooltip: const ChartTooltipConfig(enabled: true),
    ),
    ChartDefinition(
      id: 'category-value',
      title: 'Category Value',
      subtitle: 'Inventory value by category',
      chartType: ReportChartType.column,
      dataKey: 'byCategory',
      xField: 'category',
      yFields: ['value'],
      tooltip: const ChartTooltipConfig(enabled: true),
      yAxis: const ChartAxisConfig(title: 'Value (\$)'),
    ),
  ],
  grids: [
    GridDefinition(
      id: 'product-inventory',
      title: 'Product Inventory',
      subtitle: 'Complete product listing with stock levels',
      dataKey: 'products',
      columns: const [
        GridColumnDefinition(
          field: 'sku',
          title: 'SKU',
          width: 100,
        ),
        GridColumnDefinition(
          field: 'name',
          title: 'Product Name',
          width: 180,
        ),
        GridColumnDefinition(
          field: 'category',
          title: 'Category',
          width: 140,
          filterable: true,
        ),
        GridColumnDefinition(
          field: 'stock',
          title: 'Stock',
          width: 80,
          columnType: ColumnType.numeric,
          alignment: ColumnAlignment.right,
          aggregate: 'sum',
        ),
        GridColumnDefinition(
          field: 'reorderLevel',
          title: 'Reorder At',
          width: 100,
          columnType: ColumnType.numeric,
          alignment: ColumnAlignment.right,
        ),
        GridColumnDefinition(
          field: 'unitCost',
          title: 'Unit Cost',
          columnType: ColumnType.numeric,
          alignment: ColumnAlignment.right,
          formatString: '#,##0.00',
        ),
        GridColumnDefinition(
          field: 'totalValue',
          title: 'Total Value',
          columnType: ColumnType.numeric,
          alignment: ColumnAlignment.right,
          formatString: '#,##0',
          aggregate: 'sum',
        ),
        GridColumnDefinition(
          field: 'status',
          title: 'Status',
          width: 110,
          filterable: true,
        ),
        GridColumnDefinition(
          field: 'lastRestocked',
          title: 'Last Restocked',
          width: 130,
          columnType: ColumnType.date,
        ),
      ],
      sorting: const GridSortConfig(field: 'stock', ascending: true),
      allowFiltering: true,
      paging: const GridPagingConfig(pageSize: 20),
      summaries: const [
        GridSummaryConfig(field: 'stock', type: 'sum', title: 'Total Stock'),
        GridSummaryConfig(field: 'totalValue', type: 'sum', title: 'Total Value'),
      ],
    ),
  ],
  sections: const [
    SectionDefinition(
      id: 'filters',
      type: SectionType.filters,
    ),
    SectionDefinition(
      id: 'kpis',
      type: SectionType.cards,
      columns: 4,
    ),
    SectionDefinition(
      id: 'charts',
      type: SectionType.charts,
      columns: 2,
    ),
    SectionDefinition(
      id: 'products-grid',
      type: SectionType.grids,
      title: 'Product Inventory',
      collapsible: true,
    ),
  ],
);
