import 'package:flutter/material.dart';

import '../../models/models.dart';

final salesDashboardDefinition = ReportDefinition(
  id: 'sales-dashboard',
  title: 'Sales Dashboard',
  description: 'Real-time sales performance overview',
  category: 'Dashboards',
  icon: Icons.point_of_sale,
  datasource: 'sales-overview',
  layout: const LayoutDefinition(
    desktopColumns: 2,
    tabletColumns: 2,
    mobileColumns: 1,
    spacing: 16,
    runSpacing: 16,
    widgets: [
      LayoutWidgetConfig(widgetId: 'filter-section', columnSpan: 2, order: 0),
      LayoutWidgetConfig(widgetId: 'cards', columnSpan: 2, order: 1, minHeight: 130),
      LayoutWidgetConfig(widgetId: 'trend-chart', columnSpan: 1, order: 2, minHeight: 400),
      LayoutWidgetConfig(widgetId: 'region-chart', columnSpan: 1, order: 3, minHeight: 400),
      LayoutWidgetConfig(widgetId: 'grid', columnSpan: 2, order: 4, minHeight: 400),
    ],
  ),
  filters: const [
    FilterDefinition(
      id: 'dateRange',
      label: 'Date Range',
      type: ReportFilterType.dateRange,
    ),
    FilterDefinition(
      id: 'region',
      label: 'Region',
      type: ReportFilterType.singleSelect,
      apiEndpoint: '/api/regions',
    ),
  ],
  cards: const [
    CardDefinition(
      id: 'totalRevenue',
      title: 'Total Revenue',
      dataKey: 'totalRevenue',
      trendKey: 'totalRevenueTrend',
      icon: Icons.attach_money,
      isCurrency: true,
      color: Colors.blue,
    ),
    CardDefinition(
      id: 'totalOrders',
      title: 'Total Orders',
      dataKey: 'totalOrders',
      trendKey: 'totalOrdersTrend',
      icon: Icons.shopping_cart,
      color: Colors.green,
    ),
    CardDefinition(
      id: 'avgOrderValue',
      title: 'Avg Order Value',
      dataKey: 'avgOrderValue',
      trendKey: 'avgOrderValueTrend',
      icon: Icons.analytics,
      isCurrency: true,
      color: Colors.orange,
    ),
    CardDefinition(
      id: 'conversionRate',
      title: 'Conversion Rate',
      dataKey: 'conversionRate',
      trendKey: 'conversionRateTrend',
      icon: Icons.trending_up,
      formatString: '#,##0.0',
      color: Colors.purple,
    ),
  ],
  charts: const [
    ChartDefinition(
      id: 'monthlyTrendChart',
      title: 'Monthly Revenue Trend',
      chartType: ReportChartType.spline,
      dataKey: 'monthlyTrend',
      xField: 'month',
      yFields: ['revenue', 'profit'],
      legend: ChartLegendConfig(visible: true, position: 'bottom'),
      tooltip: ChartTooltipConfig(enabled: true, shared: true),
      trackball: ChartTrackballConfig(enabled: true),
    ),
    ChartDefinition(
      id: 'regionSalesChart',
      title: 'Sales by Region',
      chartType: ReportChartType.doughnut,
      dataKey: 'regionSales',
      xField: 'region',
      yFields: ['revenue'],
      legend: ChartLegendConfig(visible: true, position: 'right'),
      tooltip: ChartTooltipConfig(enabled: true),
      drillDown: DrillDownDefinition(
        targetReportId: 'sales-by-country',
        paramField: 'region',
        paramKey: 'region',
        label: 'Sales in {value}',
      ),
    ),
  ],
  grids: const [
    GridDefinition(
      id: 'orderGrid',
      title: 'Recent Orders',
      dataKey: 'orderDetails',
      allowFiltering: true,
      allowColumnResize: true,
      paging: GridPagingConfig(pageSize: 10),
      columns: [
        GridColumnDefinition(field: 'orderId', title: 'Order ID'),
        GridColumnDefinition(field: 'customer', title: 'Customer'),
        GridColumnDefinition(field: 'region', title: 'Region'),
        GridColumnDefinition(field: 'product', title: 'Product'),
        GridColumnDefinition(field: 'quantity', title: 'Qty', columnType: ColumnType.numeric, alignment: ColumnAlignment.right),
        GridColumnDefinition(field: 'total', title: 'Total', columnType: ColumnType.numeric, alignment: ColumnAlignment.right, formatString: '\$#,##0'),
        GridColumnDefinition(field: 'status', title: 'Status'),
        GridColumnDefinition(field: 'date', title: 'Date', columnType: ColumnType.date),
      ],
      sorting: GridSortConfig(field: 'date', ascending: false),
    ),
  ],
  sections: const [
    SectionDefinition(id: 'filter-section', type: SectionType.filters),
    SectionDefinition(id: 'cards', type: SectionType.cards, columns: 4, columnSpan: 2),
    SectionDefinition(id: 'trend-chart', type: SectionType.charts, childIds: ['monthlyTrendChart']),
    SectionDefinition(id: 'region-chart', type: SectionType.charts, childIds: ['regionSalesChart']),
    SectionDefinition(id: 'grid', type: SectionType.grids, columnSpan: 2),
  ],
);
